# https://docs.github.com/en/github-ae@latest/actions

name: '.NET - Avanade Papo de Dev'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  buildConfiguration: Release
  
defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.buildConfiguration }}

    - name: Test
      run: dotnet test --configuration ${{ env.buildConfiguration }} --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/